name: Build and Deploy Docs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup `node`
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'
    - name: Install `jsdoc`
      run: npm install -g jsdoc@3.6.7
    - name: Install `jsdoc` theme
      run: npm install clean-jsdoc-theme
    - name: Build Documentation
      run: jsdoc -c conf.json -R README.md
    - name: Copy over Custom Style Files for theme
      run: |
        cp doc-style/fonts/* docs/fonts/
        cp doc-style/styles/* docs/styles/
        cp doc-style/logo.svg docs/logo.svg
        cp lively.morphic/assets/favicon.ico docs/favicon.ico
    - name: Upload Documentation Build
      uses: actions/upload-pages-artifact@v2
      with:
        name: docs
        path: docs/
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: docs
      - name: Delete uploaded Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: docs