name: Check PR for merging

on:
  pull_request:

concurrency:
  group: pr-allowed-to-merge-${{ github.ref_name }}
  cancel-in-progress: true
   
jobs:
  tests:
    name: Check if `lively.next` world loads and tests stay green
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.10'
      - name: Install `sultan`
        run: pip3 install sultan 
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache `lively.next` dependencies
        id: cache-lively-deps
        uses: actions/cache/restore@v3
        env:
          cache-name: lively-deps
        with:
          path: lively.next-node_modules/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('lively*/package.json') }}
      - name: Install `lively.next`
        run: |
          chmod a+x ./install.sh
          ./install.sh
      - name: Cache `lively.next` dependencies
        if: ${{ steps.cache-lively-deps.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        env:
          cache-name: lively-deps
        with:
          path: lively.next-node_modules/            
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('lively*/package.json') }}
      - name: Check if Bundled Artifacts are up to Date 
        run:  ./scripts/check-build-status.py
      - name: Run CI Test Script for Changed Folders
        run:  ./scripts/test.sh $(./scripts/tests_for_branch.sh)
      - name: Start the lively server
        run: |
          chmod a+x ./start-server.sh
          ./start-server.sh > /dev/null 2>&1 &
          # wait until server is guaranteed to be running
          sleep 30
      - name: Run boot check script
        run: |
          chmod a+x ./scripts/check-boot.sh
          ./scripts/check-boot.sh