name: Check Docs Build

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
    - name: Install jsdocs
      run: npm install -g jsdoc
    - name: Install jsodc theme
      run: npm install clean-jsdoc-theme
    - name: Build docs
      run: jsdoc -c conf.json -R README.md
