name: Run Tests

on:
  schedule:
    - cron: "0 0 * * MON-FRI"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: Install lively.next
        run: |
          chmod a+x ./install.sh
          ./install.sh
      - name: Run CI Test Script 
        run:  ./scripts/ci-tests.sh